name: codesniffer

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging"  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: get codesniffer with moodle standaRT
      run: git clone https://github.com/moodlehq/moodle-local_codechecker.git
    - name: select correct directory
      run: cd moodle-local_codechecker/vendor/bin/
    
    # - name: setup moodle code standart
    #   run: ./moodle-local_codechecker/vendor/bin/phpcs --config-set installed_paths  ./moodle-local_codechecker/vendor/moodlehq/moodle-cs , ./moodle-local_codechecker/vendor/phpcompatibility/php-compatibility , ./moodle-local_codechecker/vendor/phpcsstandards/phpcsextra , ./moodle-local_codechecker/vendor/phpcsstandards/phpcsutils


    # - name: select moodle code standart
    #   run: ./moodle-local_codechecker/vendor/bin/phpcs --config-set default_standard moodle
    - name: debug
      run: ls

    - name: run the codesniffer
      run: ./moodle-local_codechecker/vendor/bin/phpcs ../../../server/moodle/mod/livequiz/ 